Update package.json
When try to run the backend the terminal show error mesages like this : 
```../node_modules/jest-diff/build/printDiffs.d.ts:8:13 - error TS1005: '=' expected.```

I made changes in the typescript version and the project compiled!